# https://gitlab.com/gableroux/gitlab_ci_flutter_example/blob/master/.gitlab-ci.yml
# Siehe auch: https://medium.com/@chima_37359/setup-gitlab-ci-in-flutter-android-project-89f6628828e8
stages:
  - build_and_test
  - deploy_coverage
  - deploy_backend

unit_tests_app:
  image: gableroux/flutter:latest
  stage: build_and_test
  script:
    - cd sammel_app
    - flutter test --coverage
    - genhtml coverage/lcov.info --output=coverage
  artifacts:
    paths:
      - sammel_app/coverage/
  coverage: '/^lines\.+: |\d+\.?\d+\%/'

build_android_apk:
  image: gableroux/flutter:latest
  stage: build_and_test
  script:
    - cd sammel_app
    - flutter build apk --release
  artifacts:
    paths:
      - sammel_app/build/app/outputs/apk/release/

pages:
  image: alpine
  stage: deploy_coverage
  dependencies:
    - unit_tests_app
  script:
    - mkdir public
    - mv sammel_app/coverage/ public/coverage/
  artifacts:
    paths:
      - public
  only:
    - master

test_server:
  image: maven:latest
  stage: build_and_test
  script:
    - cd sammel_server
    - mvn test -fae

build_server:
  image: maven:latest
  stage: build_and_test
  script:
    - cd sammel_server
    - mvn install -DskipTests
  artifacts:
    paths:
      - sammel_server/target

push_server:
  image: docker:latest
  stage: deploy_backend
  dependencies:
    - build_and_test
  script:
    - docker build sammel_server -t kybernetik/sammel-server:latest
    - docker push kybernetik/sammel-app:sammel-server