version: '3.4'
services:
  db:
    build: .
    container_name: server
    restart: always
    environment: {***REMOVED***
    ports:
      - '19990:9990'
      - '18080:8080'
    expose:
      - '19990'
      - '18080'