version: '3.4'
services:
  db:
    build: .
    container_name: server
    restart: always
    environment: {}
    ports:
      - '19990:9990'
      - '18080:8080'
      - '18443:8443'
    expose:
      - '19990'
      - '18443'