version: '3.4'
services:
  server:
    build: .
    container_name: server
    restart: always
    environment:
      - DB_URL=<DB_URL>
      - DB_PORT=<DB_PORT>
      - DB_SCHEMA=<DB_SCHEMA>
      - DB_USER=<DB_USER>
      - DB_PASSWORD=<DB_PASSWORD>
      - KEY_PASSWORD=<KEY_PASSWORD>
    ports:
      - '19990:9990'
      - '18080:8080'
      - '18443:8443'
    expose:
      - '19990'
      - '18443'