POST http://127.0.0.1:18080/service/termine/neu
Accept: application/json
Content-Type: application/json
Authorization: Basic MTE6YWM0MzA5NjAtMDVlYi0xMWViLThhMjYtZmRjNzY4M2E4NGJj

{
  "token": "token3",
  "action": {
    "typ": "Sammeln",
    "beginn": "2020-02-05T09:00:00",
    "ende": "2020-02-05T12:00:00",
    "ort": "Regierungsviertel",
    "latitude": 52.52116,
    "longitude": 13.41331,
    "participants": [
      {
        "id": 11,
        "name": "Karl Marx",
        "color": 1
      },
      {
        "id": 12,
        "name": "Rosa Luxemburg",
        "color": 2
      }
    ],
    "details": {
      "beschreibung": "eine andere beschreibung",
      "kontakt": "kalle@revo.de",
      "treffpunkt": "Weltzeituhr"
    }
  }
}

###

