POST http://127.0.0.1:18080/service/benutzer/neu
Accept: */*
Cache-Control: no-cache
Content-Type: application/json

{
  "secret": "geheimnis",
  "firebasKey": "firebase key",
  "benutzer": {
    "name": "Karl Marx",
  }
}

###

