POST http://127.0.0.1:18080/service/termine
Accept: application/json
Content-Type: application/json
Authorization: Basic MTE6YWM0MzA5NjAtMDVlYi0xMWViLThhMjYtZmRjNzY4M2E4NGJj

{
  "typen": [
    "Sammeln"
  ],
  "tage": [
    "2020-02-05"
  ],
  "von": "08:00:00",
  "bis": "18:00:00",
  "orte": [
    {
      "id": 1,
      "bezirk": "Friedrichshain-Kreuzberg",
      "ort": "Friedrichshain Nordkiez"
    ***REMOVED***
  ]
***REMOVED***

<> 2019-10-05T053122.200.json

###

