POST http://127.0.0.1:18080/service/termine
Accept: application/json
Content-Type: application/json
Authorization: Basic MTE6YWM0MzA5NjAtMDVlYi0xMWViLThhMjYtZmRjNzY4M2E4NGJj

{
  "typen": null,
  "tage": null,
  "von": null,
  "bis": null,
  "orte": null,
  "nurEigene": false,
  "immerEigene": true
***REMOVED***

<> 2019-10-05T053122.200.json

###

